### ISSUE TITLE
请问除了go和阿帕奇还要什么环境

### ISSUE THREAD

**Issue by valetzx** [pretty66/websocketproxy#2]
![image](https://user-images.githubusercontent.com/45054400/164390739-68b40fcc-8796-45ee-b650-19358121f523.png)

想在 replit 部署

**Comment by peecode** [comment]
不需要什么依赖，直接就能用。

**Comment by pretty66** [comment]
这是一个提供给go语言使用的库，你可以把他集成在你的项目代码中，不依赖apache
