### ISSUE TITLE
将【pretty66 / websocketproxy】和Beego2.0链接起来使用

### ISSUE THREAD

**Issue by peecode** [pretty66/websocketproxy#3]
1、我用的golang1.15.6版本在72行代码提示【logger: log.Default(),】没找到log.Default函数，直接删除改行代码即可。
2、将源代码中的【Proxy】函数名称，修改为【ServeHTTP】。
3、在Beego侧的注入方式是：
wp, err := websocketproxy.NewProxy("ws://localhost:1884/mqtt", func(r *http.Request) error {
	// 权限验证
	r.Header.Set("Cookie", "----")
	// 伪装来源
	r.Header.Set("Origin", "http://82.157.123.54:9010")
	return nil
	})
	if err != nil {
		logs.GetLogger().Println(err)
		os.Exit(999)
	}
	web.Handler("/wsproxy", wp)

Mqtt服务器使用的是Mosquitto1.6.12 for windows64bit。
希望对后来的Beego同学能够有点帮助。

**Comment by pretty66** [comment]
感谢你发现并告知了关于log库使用的一个版本问题，现在已经修复了。并且新增了http.Handler接口的实现
### 接口实现
https://github.com/pretty66/websocketproxy/blob/75c8ff34e019401a6155b1ebe8293b239b628ad9/proxy.go#L84-L86

### 使用例子：
https://github.com/pretty66/websocketproxy/blob/75c8ff34e019401a6155b1ebe8293b239b628ad9/proxy_test.go#L19-L26
