### ISSUE TITLE
请教下两个关于性能的问题

### ISSUE THREAD

**Issue by ericjing83** [pretty66/websocketproxy#5]
1.把这个开发项目的API集成到自己的go开发项目里，相比用nginx进行wss的代理，性能上有什么优势？
2.我看到proxy.go里面使用了net/http的包，如果用fasthttp，是不是性能会更好一点。不知道当前的项目有没有基于fasthttp的版本？
谢谢啦。

**Comment by pretty66** [comment]
1. 首先nginx是很优秀的代理，具体用哪个看项目需求；这是一个纯go语言的ws代理库，可以集成到项目代码里进行定制化的功能开发；性能上这个库只在协议升级时进行http数据包的解析，升级完成后只进行tcp流量的透传，工作在4层，性能完全不用担心。
2. 使用fasthttp意义不大，像上面描述的一样这个代理库只会在协议升级时进行http协议解析，剩余流程都是流量透传；fasthttp优秀在内存池、协程池、连接池的设计上。这些优秀的特性在这里都用不到，因为这个工作在4层，唯一的内存池优化技术库里面已经实现了。

如果现有的fasthttp项目想集成这个库，目前这个版本还不支持，如果有需要的话，我可以实现下
